steps:
  # Step 3: Faz o deploy da nova imagem no Cloud Run
  # O Cloud Build automaticamente faz o push das imagens taggeadas (definidas no campo 'images' abaixo)
  # para o Google Artifact Registry (ou Container Registry).
  # Este passo implanta a imagem recém-construída no serviço Cloud Run.
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'controle-financeiro-api'  # Nome do serviço Cloud Run criado pelo Terraform
      - '--image'
      - 'gcr.io/$PROJECT_ID/finance-app:$SHORT_SHA'  # Usa a imagem taggeada com o SHA do commit
      - '--region'
      - '${_REGION}'  # Região onde o Cloud Run está implantado (definida nas substituições)
      - '--platform'
      - 'managed'
      - '--service-account'
      - ontrole-financeiro-run-sa@$PROJECT_ID.iam.gserviceaccount.com'
            - '--allow-unauthenticated'# Service Account criado pelo Terraform 

  # Se sua aplicação não precisa ser acessível publicamente sem autenticação,
  # REMOVA ou COMENTE a linha abaixo. Para uma API de controle financeiro,
  # é provável que você queira que ela seja autenticada.

  # Define as imagens Docker que serão automaticamente enviadas para o Google Artifact Registry
  # após o sucesso do passo de build.
images:
  - 'gcr.io/$PROJECT_ID/finance-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/finance-app:latest'

# Substituições padrão.
# A variável '_REGION' é usada para especificar a região do Cloud Run.
# É crucial que esta região corresponda à região que você definiu no seu arquivo Terraform.
# Você pode sobrescrever '_REGION' ao configurar o trigger do Cloud Build ou ao iniciar um build manualmente.
substitutions:
  southamerica-east1rica-east1  # <-- ATENÇÃO: Altere para a região que você usou no Terraform (ex: southamerica-east1)

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
